# Generated by Django 3.1.2 on 2021-04-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0002_turf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='image3',
        ),
    ]
