# Generated by Django 3.1.2 on 2021-04-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0005_stadium_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='type',
        ),
    ]
