# Generated by Django 3.1.2 on 2021-04-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0008_stadium_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_date', models.CharField(max_length=50)),
                ('t_date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turf.stadium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turf.userreg')),
            ],
        ),
    ]
