# Generated by Django 3.1.2 on 2021-04-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0009_bookstadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstadium',
            name='bdate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
