# Generated by Django 3.1.2 on 2021-04-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0010_bookstadium_bdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstadium',
            name='forwhat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
