# Generated by Django 3.1.2 on 2021-04-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0011_bookstadium_forwhat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTurf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('noh', models.CharField(max_length=50)),
                ('forwhat', models.CharField(max_length=50, null=True)),
                ('total', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turf.turf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turf.userreg')),
            ],
        ),
    ]
