# Generated by Django 3.2 on 2021-04-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0014_auto_20210424_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='fdate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='tdate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
